"use client";

import { useState } from "react";
import { Navbar } from "@/components/Navbar";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Sparkles, Zap, Target, LayoutTemplate, Share2, Award, ArrowRight } from "lucide-react";
import Link from "next/link";
import { generateLogo } from "@/lib/logo";

export default function Home() {
  const [name, setName] = useState("");
  const [industry, setIndustry] = useState("");
  const [tone, setTone] = useState("");
  const [logo, setLogo] = useState("");
  const [loading, setLoading] = useState(false);

  const handleGenerateLogo = async () => {
    if (!name || !industry || !tone) {
      alert("Please fill all fields");
      return;
    }

    try {
      setLoading(true);
      const res = await generateLogo(name, industry, tone);
      setLogo(res.logo);
    } catch (err) {
      alert("Logo generation failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="min-h-screen bg-white text-gray-900 dark:bg-dark-bg dark:text-white">
      <Navbar />

      {/* HERO */}
      <section className="relative overflow-hidden pt-32 pb-20 md:pt-48 md:pb-32">
        <div className="mx-auto max-w-7xl px-6">
          <div className="grid gap-12 lg:grid-cols-2 lg:items-center">
            <div className="max-w-2xl">
              <div className="mb-6 inline-flex items-center rounded-full border border-brand-200 bg-brand-50 px-3 py-1 text-sm font-medium text-brand-700">
                <Sparkles className="mr-2 h-4 w-4" />
                AI Branding Co-Founder
              </div>

              <h1 className="mb-6 text-5xl font-bold md:text-6xl">
                Build a Complete Brand in Minutes
              </h1>

              <p className="mb-8 text-xl text-gray-600">
                Name, logo, content, strategy, and brand score — all generated by AI.
              </p>

              <Link href="/dashboard">
                <Button size="lg">
                  Start Branding <ArrowRight className="ml-2 h-5 w-5" />
                </Button>
              </Link>
            </div>

            <div className="hidden lg:block">
              <Card className="p-8">
                <p className="text-lg font-semibold">AI Generated Preview</p>
                <div className="grid grid-cols-2 gap-4 mt-6">
                  <div className="aspect-square rounded bg-indigo-100" />
                  <div className="aspect-square rounded bg-purple-100" />
                </div>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section className="py-24 bg-gray-50">
        <div className="mx-auto max-w-7xl px-6 grid gap-8 md:grid-cols-3">
          {[
            { icon: Zap, title: "Brand Name Generator", desc: "Catchy names instantly." },
            { icon: LayoutTemplate, title: "Logo Generator", desc: "Unique AI logos." },
            { icon: Share2, title: "Social Media Kit", desc: "Ready-to-post content." },
            { icon: Award, title: "Brand Score", desc: "AI business analysis." },
            { icon: Target, title: "Market Analysis", desc: "Position your brand." },
            { icon: Sparkles, title: "Founder Story", desc: "Tell your story." },
          ].map((f, i) => (
            <Card key={i} className="p-6">
              <f.icon className="mb-4 h-6 w-6 text-brand-600" />
              <h3 className="font-bold text-xl mb-2">{f.title}</h3>
              <p className="text-gray-600">{f.desc}</p>
            </Card>
          ))}
        </div>
      </section>

      {/* 🔥 LIVE LOGO GENERATOR */}
      <section className="py-24 bg-white text-center">
        <div className="max-w-4xl mx-auto px-6">
          <h2 className="text-3xl font-bold mb-4">Try Live AI Logo Generator</h2>
          <p className="text-gray-600 mb-10">Generate a real logo instantly.</p>

          <div className="flex flex-col md:flex-row gap-4 justify-center">
            <input
              placeholder="Brand Name"
              className="p-3 border rounded w-full md:w-1/3 text-black"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
            <input
              placeholder="Industry"
              className="p-3 border rounded w-full md:w-1/3 text-black"
              value={industry}
              onChange={(e) => setIndustry(e.target.value)}
            />
            <input
              placeholder="Tone (modern, luxury...)"
              className="p-3 border rounded w-full md:w-1/3 text-black"
              value={tone}
              onChange={(e) => setTone(e.target.value)}
            />
          </div>

          <Button className="mt-6" onClick={handleGenerateLogo}>
            {loading ? "Generating..." : "Generate Logo"}
          </Button>

          {logo && (
            <div className="mt-12">
              <h3 className="text-xl font-semibold mb-4">Generated Logo</h3>
              <img src={logo} className="mx-auto w-72 rounded shadow-lg" />
            </div>
          )}
        </div>
      </section>

      <footer className="border-t py-12 text-center text-gray-500">
        © 2026 BrandCraft AI
      </footer>
    </main>
  );
}